### ISSUE TITLE
Error: module 'OpenSSL.crypto' has no attribute 'sign'

### ISSUE THREAD

**Issue by petr-simon** [patrickwyler/gcs-bucket-sync-action#11]
Hello, from 2024-12-11 this action returns

`module 'OpenSSL.crypto' has no attribute 'sign'`

Do you have some suggestions?

![image](https://github.com/user-attachments/assets/57a207a0-07bb-43d6-aeeb-bcab8a7e810c)

**Comment by patrickwyler** [comment]
Can't investigate it now.. will have a look at it in a few days. Was it working before?

**Comment by jb-72** [comment]
Also have the same issue. 

Looks like an issue with https://github.com/GoogleCloudPlatform/cloud-sdk-docker

[https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/497](url)

**Comment by patrickwyler** [comment]
Thanks for the hint! Changed the docker version for now to the last working one which was mentioned there. Instead of using the action with the version tag "1.4" you could use "master" for now. Couldn't test it yet and can't release a new version on my mobile phone.

**Comment by petr-simon** [comment]
Thank you! I tested action from "main" branch and it works like before.

**Comment by patrickwyler** [comment]
Will rollback my changes.. the cloud-sdk issue got fixed and version 1.4 should work again.

**Comment by jb-72** [comment]
Hi Patrick. Looks like this issue is back. Just started seeing this error today:

`module 'OpenSSL.crypto' has no attribute 'sign'`

Any suggestions?

Thanks

**Comment by pvanacker** [comment]
Hello. Same error here. It would be great if you could take a look :) Thanks !

**Comment by jb-72** [comment]
Seems to be resolved now @pvanacker

**Comment by pvanacker** [comment]
Indeed, thanks for letting me know @jb-72 !
