### ISSUE TITLE
Setting `Content-Type` for `.css` files

### ISSUE THREAD

**Issue by akaihola** [patrickwyler/gcs-bucket-sync-action#5]
Before trying out this action, I wanted to ask whether it will allow `.css` stylesheet files to work correcly on a published website?

I'm asking because I've previously needed to do the following when uploading my static website using `gsutil` (this is from my `Makefile`):
```Makefile
ROOT_DIR:=$(dir $(realpath $(lastword $(MAKEFILE_LIST))))

upload: upload-files fix-content-types

upload-files:
	gsutil \
	  rsync \
		-R \
		-d $(ROOT_DIR)html \
		gs://www.palindromi.fi

fix-content-types:
	gsutil setmeta \
	  -h "Content-Type:text/html" \
	  gs://www.palindromi.fi/*
	gsutil setmeta \
	  -h "Content-Type:text/css" \
	  gs://www.palindromi.fi/static/*.css
```

**Comment by patrickwyler** [comment]
Why did you have to set the content type manually? I'm using this action for my own [website](www.patrickwyler.com) which is working without any special fixes. If there is a good reason for it, may it would make sense to implement it too.

My website project: https://github.com/patrickwyler/patrickwyler.com

**Comment by patrickwyler** [comment]
Just checked my bucket and my content-types are correct.

![Screenshot 2023-02-27 at 10 37 36](https://user-images.githubusercontent.com/23375188/221528520-8154a80d-c01e-41c2-823f-e877c17c4574.png)

**Comment by akaihola** [comment]
Thanks @patrickwyler for pointing this out. It's been ~3 years since I updated my site, so maybe something has improved since then. Or maybe I just missed something back then.

Anyway, this is good news! I can just use your action when taking GitHub workflows into use, instead of continuing with my own scripts.
