### ISSUE TITLE
is there anyway to set metadata content-type on upload? 

### ISSUE THREAD

**Issue by 65156** [patrickwyler/gcs-bucket-sync-action#7]
im serving some webfiles from a bucket without an extension (.html), id like to be able to ensure the content-type metadata property is preserved as (text/html), It seems to be removed after sync.

**Comment by 65156** [comment]
https://cloud.google.com/storage/docs/metadata?authuser=1&_ga=2.155380219.-118707203.1677198202&_gac=1.83826020.1684438279.Cj0KCQjwmZejBhC_ARIsAGhCqnf7m5EDZlDn-_mexwW0MXytBQTKQRDlefE9_-bsTkjW1w_l4RYgBqIaAhlaEALw_wcB#content-type

**Comment by 65156** [comment]
Seems like when its uploaded the content is scanned and google takes a guess at the content type, it can be explicitly specified at upload.

**Comment by patrickwyler** [comment]
Right now there is no way to configure a default content type for files without a file extension.


Maybe a workaround like this could fix your issue: https://github.com/patrickwyler/gcs-bucket-sync-action/issues/5#issue-1599678460

**Comment by 65156** [comment]
thanks for your response, this is helpful

it looks like ill need to use gsutil to set it manually in a follow up task.
